# Generated by Django 2.1.2 on 2018-10-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='slot',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
