# Generated by Django 2.1.2 on 2018-10-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_drug_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='slot',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
