# Generated by Django 2.1.2 on 2018-10-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20181013_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='slot',
        ),
        migrations.AddField(
            model_name='schedule',
            name='drugs',
            field=models.TextField(null=True),
        ),
    ]
