# Generated by Django 2.1.2 on 2018-10-14 01:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20181013_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='first_dispense',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
