# Generated by Django 2.1.2 on 2018-10-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_schedule_first_dispense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='first_dispense',
            new_name='next_dispense',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='drugs',
        ),
        migrations.AddField(
            model_name='schedule',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='drug',
            field=models.CharField(default='advil', max_length=30),
        ),
    ]
