# Generated by Django 2.1.2 on 2018-10-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20181013_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='next_dispense',
            field=models.DateTimeField(),
        ),
    ]
