# Generated by Django 2.1.2 on 2018-10-14 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20181013_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='next_dispense',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 14, 3, 45, 13, 706044)),
        ),
    ]
