# Generated by Django 2.1.2 on 2018-10-14 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20181014_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=30)),
                ('reset', models.CharField(default='false', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='next_dispense',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 14, 1, 35, 39, 989200)),
        ),
    ]
