# Generated by Django 2.1.2 on 2018-10-14 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20181014_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reset',
            old_name='reset',
            new_name='val',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='next_dispense',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 14, 1, 38, 30, 163367)),
        ),
    ]
